spring.application.name=Mubak!
<<<<<<< HEAD
spring.datasource.url=jdbc:h2:file:./data/mubak
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
=======
spring.datasource.url=${SUPABASE_DB_URL:jdbc:h2:mem:mubak}
spring.datasource.username=${SUPABASE_DB_USERNAME:sa}
spring.datasource.password=${SUPABASE_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create-drop}
>>>>>>> dde1454008ef259cd4dd14280c3ec8c0fb8eb6cb
spring.jpa.show-sql=false
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.thymeleaf.cache=false
